//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JakeMud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Path
    {
        public int PathID { get; set; }
        public short CurrMapID { get; set; }
        public short NextMapID { get; set; }
        public string Direction { get; set; }
        public bool Lock { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual Map Map { get; set; }
        public virtual Map Map1 { get; set; }
    }
}
